//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineTask
    {
        public System.Guid Id { get; set; }
        public string UsageStart { get; set; }
        public string UsageEnd { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public Nullable<System.Guid> machine_Id { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
