//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> Details_Id { get; set; }
        public Nullable<System.Guid> EdvActions_Id { get; set; }
        public Nullable<System.Guid> ProductionActions_Id { get; set; }
        public Nullable<int> Versionierung { get; set; }
    
        public virtual EdvActions EdvActions { get; set; }
        public virtual OrderDetails OrderDetails { get; set; }
        public virtual ProductionActions ProductionActions { get; set; }
    }
}
